name: Activity Filters
on: 
  pull_request:
    types: [synchronize]
  workflow_dispatch:

jobs:
  any-old-job-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Any Old Step
        run: echo "yada dada"
