name: Demo Github Actions
on: workflow_dispatch

jobs:
   first-demo-job:
     runs-on: ubuntu-latest
     steps:
       -name: First step
        run: echo "This is a stp within a job within a workflow"
       -name: List All Files in Current Directory
        run: ls -lart
