name: Demo Github Actions

on: 
  workflow_dispatch:

jobs:
  checkout_git-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rep
        uses:  actions/checkout@v4
      - name: Install Tree
        run: sudo apt install tree -y
        name: investigative repo
        run: 
         pwd
         ls -lart


